### ISSUE TITLE
Static assets

### ISSUE THREAD

**Issue by stevetoro** [alyppyo/prj-rev-bwfs-dasmoto#1]
https://github.com/alyppyo/prj-rev-bwfs-dasmoto/blob/master/DasmotoProject/index.html#L5

Great job writing a relative file path to your stylesheet. This makes it easy for anyone to clone your project on any computer and immediately see your styled project 👍 

https://github.com/alyppyo/prj-rev-bwfs-dasmoto/blob/master/DasmotoProject/index.html#L14

Consider downloading these images and putting them in an `images` folder (inside your `resources` folder). Then you can write a relative file path to these images instead of relying on an external URL!

**Comment by alyppyo** [comment]
In the project first version I did it. However, I've deleted the directory before sending the project because I wanted to keep it similar to the examples seen in the lessons. I will put the directory in the project again.

**Comment by alyppyo** [comment]
Done.
