### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [alyppyo/prj-rev-bwfs-dasmoto#5]
https://github.com/alyppyo/prj-rev-bwfs-dasmoto/blob/master/DasmotoProject/resources/css/index.css#L1-L3

Good job avoiding repetition by using the universal selector 👍 

`font-weight: bold;` appears in a lot of rules. Maybe you could put this style into a single rule with multiple selectors to eliminate repetition altogether.

**Comment by alyppyo** [comment]
Done!
