### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by stevetoro** [alyppyo/prj-rev-bwfs-dasmoto#6]
Satisfactory 👍 

Great job reproducing the web page according to the design mock. You've written some very organized HTML & CSS as well, good job!

See if you can improve the organization of your HTML even more by using `div`s to divide your page into sections. Make sure you also correct your `span` tags 😄 

Keep up the great work!

**Comment by alyppyo** [comment]
Thank you for the tips! That one about the bold elements did pass under my radar. Looking forward to the next assignment!
